import type {NextPage} from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1>
          Welcome to Wakaf Tech
        </h1>
        <p>Get started by editing{' '}</p>
      </main>

      <footer>
        Powered by Wakaf Tech
      </footer>
    </div>
  )
}

export default Home
