import { getUser } from "@supabase/auth-helpers-nextjs";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { Hero } from "../ui/Hero";
import { Navbar } from "../ui/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>go.mmo.sg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Hero />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { user } = await getUser(context);
  if (user) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
